logoText = "Leeifme's Blog"
logoType = "short" # long, short
description = "leeifme,blog,ç¡æ²™å‘ã®æ²™çš®ç‹—,leeif.me,golang,kubernetes,k8s,docker,Backend Developer,ç ”å‘"
custom_css = []
custom_js = []
useFaviconGenerator = false # https://www.favicon-generator.org/

themeOptions = ["dark", "light", "hacker", "solarized"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume","gallery"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume","gallery"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false

# header
homeHeaderType = "img" # text, img, slide

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

# navbar
enableThemeChange = true # site color theme

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20

# whoami
myname = "ç¡æ²™å‘ã®æ²™çš®ç‹—"
email = "i@leeif.me"
whoami = "ğŸ‘¨â€ğŸ’» Backend Developer/ğŸ“š Learner/ğŸš€ Opensource enthusiast"
bioImageUrl = "https://leeifme.oss-cn-shanghai.aliyuncs.com/blog/about/avatar.jpg"
useGravatar = false
location = "ShangHai, China"
organization = "Developer"
link = "https://leeif.me"

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "outer" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = false # another lists in the sidebar

# footer 
showPoweredBy = false 
showFeedLinks = true 
showSocialLinks = true
enableLangChange = true 

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = true
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# comment
enableComment = true
disqus_shortname = ""
commento = false

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[utterances]       # https://utteranc.es/
  owner = "leeifme"              # Your GitHub ID
  repo = "leeifme.github.io"

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = 'ä½ çš„appId'
  appKey = 'ä½ çš„appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = 'è¯´ç‚¹ä»€ä¹ˆå§...'
  visitor = false

[changyan]
  changyanAppid = ""        # Changyan app id             # ç•…è¨€
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # æ¥å¿…åŠ›

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "mailto:i@leeif.me"
  phone = ""
  facebook = ""
  twitter = "https://twitter.com/leeifme"
  github = "https://github.com/leeifme"
  stack-overflow = "https://stackoverflow.com/"
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = "https://medium.com/"
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = "https://telegram.me"
  steam = ""
  weibo = "https://weibo.com/leostones"
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""

[donationOptions]
  enable = false
  alipay = "" 
  wechat = ""
  paypal = ""
  patreon = ""
# [copyrightOptions]
#  enableCopyrightLink = true # if set, you can add copyright link
#  copyrightLink = "https://creativecommons.org/licenses/by-nc/4.0/"
#  copyrightLinkImage = "https://mirrors.creativecommons.org/presskit/buttons/80x15/svg/by-nc.svg"
#  copyrightLinkText = "CC BY-NC"

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line"]
[[share]]
  name = "facebook"
  username = "leeifme"
[[share]]
  name = "twitter"
  username = "leeifme"
[[share]]
  name = "telegram"
[[share]]
  name = "whatsapp"
[[share]]
  name = "linkedin"
[[share]]
  name = "reddit"
[[footerLinks]]
